### ISSUE TITLE
Using proxy

### ISSUE THREAD

**Issue by HaydenMeloche** [IntuitDeveloper/QBOConceptsTutorial-Java#5]
Hi I was wondering how I could use this example behind a corporate proxy? Does the SDK support custom proxy information? 

Thanks!

**Comment by diana-derose** [comment]
Hi - Yes, it is supported, you'll have to set the following properties in the config file or you can set it programmatically as well using Config.setProperty("key", "value");
https://github.com/IntuitDeveloperRelations/QuickbooksV3API-Java/blob/master/QuickbooksV3API/target/classes/intuit-config.xml
